name: ligo
dependencies:
  - python=3.9
  - numpy=2.0
  - scipy=1.13
  - h5py=3.12
  - json5=0.9
  - jsonpointer=3.0
  - jsonschema=4.23
  - jsonschema-specifications=2023.12
  - jsonschema-with-format-nongpl=4.23
  - python-fastjsonschema=2.20
  - python-json-logger=2.0
  - ipython=8.18
  - decorator=5.1
  - matplotlib=3.9
  - ipykernel=6.29